"""Configuration constants for the Executor Robot."""

EXECUTOR_ID = 2

# SPI / LoRa Pins
LORA_SPI_BUS = 0
LORA_SPI_CS = 0
LORA_CE0 = 8
LORA_RST = 22
LORA_DIO0 = 25

# I2C Addresses
I2C_BUS = 1
INA219_ADDR = 0x40
MPU9250_ADDR = 0x68

# ADC Channels (MCP3008 via SPI or I2C ADC)
ADC_MQ2_CH = 0
ADC_MQ7_CH = 1

# Verification Thresholds
THERMAL_BODY_MIN = 34.0
THERMAL_BODY_MAX = 42.0
THERMAL_FIRE_MIN = 80.0
MQ2_SMOKE_MIN = 300
MQ7_CO_MIN = 250

# Mission Priorities
PRIORITY_VICTIM = 3
PRIORITY_FIRE = 2
PRIORITY_GAS = 1
PRIORITY_CHECKPOINT = 0

# RSSI Homing Parameters
RSSI_CLOSE = -40
RSSI_NEAR = -60
RSSI_FAR = -80

# Navigation Speeds
APPROACH_SPEED = 0.5
SEARCH_SPEED = 0.8
SAFE_DISTANCE_HAZARD = 1.0  # meters

# Battery Thresholds
BATTERY_LOW = 20.0
BATTERY_CRITICAL = 10.0
